apiVersion: v1
kind: Pod
metadata:
  name: slow-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim-slow
  containers:
    - name: busybox-a
      image: alpine:latest
      command:
      - sleep
      - "3600"
      volumeMounts:
      - name: pv-storage
        mountPath: /pv-data
