apiVersion: v1
kind: Pod
metadata:
  name: select-pod
spec:
  nodeSelector:
    goodrun: "yes"
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - sleep
      - "3600"
  # tolerations:
  # - key: "smell"
  #   operator: "Exists"
  #   effect: "NoSchedule"    